spring.application.name=reservation-pay

#db
spring.datasource.url=jdbc:mysql://localhost:3306/pay_reservation?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=ydh
spring.datasource.password=1234